## 1.ndarray常见的数据类型

In [3]:
import numpy as np

In [4]:
arr1 = np.arange(10)
arr2 = np.random.rand(10)
arr3 = np.array(['hello', 'python', 'hello', 'world'])
arr4 = np.array([True, False, True, False])

class Obj(object):
    pass

arr5 = np.array([Obj(), Obj(), Obj(), Obj()])

In [5]:
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print(arr4.dtype)
print(arr5.dtype)

int32
float64
<U6
bool
object


## 2. 创建ndarray时通过dtype参数指定数据类型

In [8]:
arr6 = np.arange(10, dtype=float)
print(arr6)

arr7 = np.ones((3, 4), dtype=str)
print(arr7)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


## 3. 创建后通过 astype() 方法修改ndarray的数据类型

In [9]:
print(arr6.astype(int))

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print(arr7.astype(float))

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
