In [1]:
import numpy as np

## 1.一元元素计算函数

In [3]:
arr1 = np.random.uniform(-5, 10, (3, 4))
print(arr1)

[[ 2.70712497  1.41781092  0.1915691   7.46884948]
 [-3.17572741  1.06769273 -3.86985887  4.2969882 ]
 [ 0.6100757  -4.7861959   2.17143444  5.56076463]]


In [5]:
## 1. ceil() 求元素向上最接近的整数
print(np.ceil(arr1))

[[ 3.  2.  1.  8.]
 [-3.  2. -3.  5.]
 [ 1. -4.  3.  6.]]


In [6]:
## 2. 求元素向下最接近的整数
print(np.floor(arr1))

[[ 2.  1.  0.  7.]
 [-4.  1. -4.  4.]
 [ 0. -5.  2.  5.]]


In [7]:
## 3. rint() 求四舍五入
print(np.rint(arr1))

[[ 3.  1.  0.  7.]
 [-3.  1. -4.  4.]
 [ 1. -5.  2.  6.]]


In [8]:
## 4. abs() 求绝对值
print(np.abs(arr1))

[[ 2.70712497  1.41781092  0.1915691   7.46884948]
 [ 3.17572741  1.06769273  3.86985887  4.2969882 ]
 [ 0.6100757   4.7861959   2.17143444  5.56076463]]


In [9]:
## 5. negative() 元素取反
print(np.negative(arr1))

[[-2.70712497 -1.41781092 -0.1915691  -7.46884948]
 [ 3.17572741 -1.06769273  3.86985887 -4.2969882 ]
 [-0.6100757   4.7861959  -2.17143444 -5.56076463]]


In [10]:
## 6. square()求元素的平方
print(np.square(arr1))

[[  7.32852561e+00   2.01018782e+00   3.66987212e-02   5.57837125e+01]
 [  1.00852446e+01   1.13996777e+00   1.49758077e+01   1.84641076e+01]
 [  3.72192354e-01   2.29076712e+01   4.71512753e+00   3.09221032e+01]]


In [11]:
## 7. sqrt()求元素的平方根
print(np.sqrt(arr1))

[[ 1.6453343   1.19071866  0.43768608  2.73291959]
 [        nan  1.03329218         nan  2.0729178 ]
 [ 0.78107343         nan  1.47357879  2.35812736]]


C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


In [12]:
## 8. isnan() 判断是否是NaN, 返回bool类型数组, 如果元素是nan, 返回True, 否则返回False
print(np.isnan(arr1))

[[False False False False]
 [False False False False]
 [False False False False]]


In [13]:
## 凡是bool类型的数据, 都可以用条件索引
## 得出数组里不能求平方根的数字
print(arr1[np.isnan(np.sqrt(arr1))])

[-3.17572741 -3.86985887 -4.7861959 ]


C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
## 9. sign()判断元素的正负, 正数返回1, 负数返回-1, 0返回0

In [14]:
print(np.sign(arr1))

[[ 1.  1.  1.  1.]
 [-1.  1. -1.  1.]
 [ 1. -1.  1.  1.]]


In [15]:
## 10.modf() 将数组拆分为小数部分和整数部分两个数组(整个结果是二维数组)

In [17]:
print(np.modf(arr1)[0])
print(np.modf(arr1)[1])

[[ 0.70712497  0.41781092  0.1915691   0.46884948]
 [-0.17572741  0.06769273 -0.86985887  0.2969882 ]
 [ 0.6100757  -0.7861959   0.17143444  0.56076463]]
[[ 2.  1.  0.  7.]
 [-3.  1. -3.  4.]
 [ 0. -4.  2.  5.]]


## 2.二元元素计算函数

In [18]:
arr2 = np.arange(10)
arr3 = np.arange(10, 20)
print(arr2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [20]:
## 1. add() 将两个数组的数值按下标相加, 返回一个新的数组
print(np.add(arr2, arr3))

[10 12 14 16 18 20 22 24 26 28]


In [21]:
## 2. subtract() 将两个数组的数值按下标相减,返回一个新的数组
print(np.subtract(arr3, arr2))

[10 10 10 10 10 10 10 10 10 10]


In [22]:
## 3. multiply() 将两个数组的数值按下标相乘, 返回一个新的数组
print(np.multiply(arr2, arr3))

[  0  11  24  39  56  75  96 119 144 171]


In [ ]:
## 4. divide() 将两个数组的数值按下标相除, 返回一个新的数组
print(np)