In [1]:
import numpy as np

## 1.数组和数组的运算

In [5]:
arr1 = np.arange(10).reshape(2, 5)
arr2 = np.arange(10, 20).reshape(2, 5)
arr3 = np.arange(5)
print(arr1)
print("-------")
print(arr2)
print("-------")
print(arr3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
-------
[[10 11 12 13 14]
 [15 16 17 18 19]]
-------
[0 1 2 3 4]


In [7]:
# 1. 多维数组和多维数组的运算
# 两个ndarray进行算术运算, 相当于按下标对应依次运算, 并返回一个新的数组
# 矩阵运算必须保证数组的维度大小一致
print(arr1 + arr2)

[[10 12 14 16 18]
 [20 22 24 26 28]]


In [8]:
# 多维数组和一维数组运算,一维数组的维度必须和多维数组的尾部维度一致
# 将多维数组拆分成多个一维数组,在依次和一维数组做运算, 并将结果合并为一个多维数组
print(arr2 + arr3)

[[10 12 14 16 18]
 [15 17 19 21 23]]


## 2.数组和数值之间的运算(广播运算)

In [9]:
print(arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
# 将数组的每个元素依次和数值进行运算, 并返回新的数组
print(arr1 * 10)

[[ 0 10 20 30 40]
 [50 60 70 80 90]]


In [11]:
print(arr1 / 10)

[[ 0.   0.1  0.2  0.3  0.4]
 [ 0.5  0.6  0.7  0.8  0.9]]
