In [1]:
import numpy as np

## 1.一元元素计算函数

In [3]:
arr1 = np.random.uniform(-5, 10, (3, 4))
print(arr1)

[[ 2.70712497  1.41781092  0.1915691   7.46884948]
 [-3.17572741  1.06769273 -3.86985887  4.2969882 ]
 [ 0.6100757  -4.7861959   2.17143444  5.56076463]]


In [5]:
## 1. ceil() 求元素向上最接近的整数
print(np.ceil(arr1))

[[ 3.  2.  1.  8.]
 [-3.  2. -3.  5.]
 [ 1. -4.  3.  6.]]


In [6]:
## 2. 求元素向下最接近的整数
print(np.floor(arr1))

[[ 2.  1.  0.  7.]
 [-4.  1. -4.  4.]
 [ 0. -5.  2.  5.]]


In [7]:
## 3. rint() 求四舍五入
print(np.rint(arr1))

[[ 3.  1.  0.  7.]
 [-3.  1. -4.  4.]
 [ 1. -5.  2.  6.]]


In [8]:
## 4. abs() 求绝对值
print(np.abs(arr1))

[[ 2.70712497  1.41781092  0.1915691   7.46884948]
 [ 3.17572741  1.06769273  3.86985887  4.2969882 ]
 [ 0.6100757   4.7861959   2.17143444  5.56076463]]


In [9]:
## 5. negative() 元素取反
print(np.negative(arr1))

[[-2.70712497 -1.41781092 -0.1915691  -7.46884948]
 [ 3.17572741 -1.06769273  3.86985887 -4.2969882 ]
 [-0.6100757   4.7861959  -2.17143444 -5.56076463]]


In [10]:
## 6. square()求元素的平方
print(np.square(arr1))

[[  7.32852561e+00   2.01018782e+00   3.66987212e-02   5.57837125e+01]
 [  1.00852446e+01   1.13996777e+00   1.49758077e+01   1.84641076e+01]
 [  3.72192354e-01   2.29076712e+01   4.71512753e+00   3.09221032e+01]]


In [11]:
## 7. sqrt()求元素的平方根
print(np.sqrt(arr1))

[[ 1.6453343   1.19071866  0.43768608  2.73291959]
 [        nan  1.03329218         nan  2.0729178 ]
 [ 0.78107343         nan  1.47357879  2.35812736]]


C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


In [12]:
## 8. isnan() 判断是否是NaN, 返回bool类型数组, 如果元素是nan, 返回True, 否则返回False
print(np.isnan(arr1))

[[False False False False]
 [False False False False]
 [False False False False]]


In [13]:
## 凡是bool类型的数据, 都可以用条件索引
## 得出数组里不能求平方根的数字
print(arr1[np.isnan(np.sqrt(arr1))])

[-3.17572741 -3.86985887 -4.7861959 ]


C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
## 9. sign()判断元素的正负, 正数返回1, 负数返回-1, 0返回0

In [14]:
print(np.sign(arr1))

[[ 1.  1.  1.  1.]
 [-1.  1. -1.  1.]
 [ 1. -1.  1.  1.]]


In [15]:
## 10.modf() 将数组拆分为小数部分和整数部分两个数组(整个结果是二维数组)

In [17]:
print(np.modf(arr1)[0])
print(np.modf(arr1)[1])

[[ 0.70712497  0.41781092  0.1915691   0.46884948]
 [-0.17572741  0.06769273 -0.86985887  0.2969882 ]
 [ 0.6100757  -0.7861959   0.17143444  0.56076463]]
[[ 2.  1.  0.  7.]
 [-3.  1. -3.  4.]
 [ 0. -4.  2.  5.]]


## 2.二元元素计算函数

In [18]:
arr2 = np.arange(10)
arr3 = np.arange(10, 20)
print(arr2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [20]:
## 1. add() 将两个数组的数值按下标相加, 返回一个新的数组
print(np.add(arr2, arr3))

[10 12 14 16 18 20 22 24 26 28]


In [21]:
## 2. subtract() 将两个数组的数值按下标相减,返回一个新的数组
print(np.subtract(arr3, arr2))

[10 10 10 10 10 10 10 10 10 10]


In [22]:
## 3. multiply() 将两个数组的数值按下标相乘, 返回一个新的数组
print(np.multiply(arr2, arr3))

[  0  11  24  39  56  75  96 119 144 171]


In [23]:
## 4. divide() 将两个数组的数值按下标相除, 返回一个新的数组
print(np.divide(arr2, arr3))

[ 0.          0.09090909  0.16666667  0.23076923  0.28571429  0.33333333
  0.375       0.41176471  0.44444444  0.47368421]


In [26]:
## 5. floor_divide() 整除 舍弃余数, 保留整数商
print(np.floor_divide(arr3, arr2))

[ 0 11  6  4  3  3  2  2  2  2]


C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [27]:
## 6. mod() 求余数 arr2 % arr3
print(np.mod(arr2, arr3))

[0 1 2 3 4 5 6 7 8 9]


In [28]:
## 7. power() 求元素的n次方， arr2 ** arr3
print(np.power(arr2, arr3))

[          0           1        4096     1594323   268435456   452807053
  -683606016 -2094633337           0  -400556711]


## 3.三元元素计算函数

In [29]:
print(arr1)

[[ 2.70712497  1.41781092  0.1915691   7.46884948]
 [-3.17572741  1.06769273 -3.86985887  4.2969882 ]
 [ 0.6100757  -4.7861959   2.17143444  5.56076463]]


In [32]:
# 迭代判断数组的每个元素, 返回的也是当前正在判断的那个元素, 而不是返回整个数组
arr4 = np.where(arr1 < 0, arr1, 0)
print(arr4)

[[ 0.          0.          0.          0.        ]
 [-3.17572741  0.         -3.86985887  0.        ]
 [ 0.         -4.7861959   0.          0.        ]]


In [35]:
# 创建两个数组
arr_1 = np.array([16, 7, 8, 2, 8, 3, 4, -5, 4, 27])
arr_2 = np.array([23, 5, 3, 7, 2, 1, 2, -2, 7, 14])

# ndarray 转换为字符串
list_1 = arr_1.tolist()
list_2 = arr_2.tolist()

In [36]:
print(list_1)
print(list_2)

[16, 7, 8, 2, 8, 3, 4, -5, 4, 27]
[23, 5, 3, 7, 2, 1, 2, -2, 7, 14]


In [37]:
# Python的列表写法
list_3 = [ x if x > y else y for x, y in zip(list_1, list_2)]
print(list_3)

[23, 7, 8, 7, 8, 3, 4, -2, 7, 27]


In [39]:
# ndarray的写法
arr_3 = np.where(arr_1 > arr_2, arr_1, arr_2)
print(arr_3)

[23  7  8  7  8  3  4 -2  7 27]


In [40]:
arr_sqrt = np.sqrt(arr1)
print(arr1)

[[ 2.70712497  1.41781092  0.1915691   7.46884948]
 [-3.17572741  1.06769273 -3.86985887  4.2969882 ]
 [ 0.6100757  -4.7861959   2.17143444  5.56076463]]


C:\Python\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


In [41]:
np.isnan(arr1)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]], dtype=bool)

In [42]:
# 课堂小练习: 现给出 np.random.uniform(10, 40, (3, 4)) 数组，找出所有四舍五入后大于20且小于30的数字，修改为100，其他数字不变，并组成新的数组

In [44]:
float_arr = np.random.uniform(10, 40, (3, 4))
print(float_arr)

[[ 31.48258957  16.6622578   35.00785286  13.83299064]
 [ 27.56009589  26.44049241  22.93098634  30.76730106]
 [ 33.28283127  37.00791716  31.33058935  11.77957355]]


In [51]:
np.where((np.rint(float_arr) > 20) & (np.rint(float_arr) < 30), 100, float_arr)

array([[  31.48258957,   16.6622578 ,   35.00785286,   13.83299064],
       [ 100.        ,  100.        ,  100.        ,   30.76730106],
       [  33.28283127,   37.00791716,   31.33058935,   11.77957355]])